### ISSUE TITLE
Facebook PHP SDK 4 supported?

### ISSUE THREAD

**Issue by m-vdv** [insolis/facebook-service-provider#2]
Does this service provider support the latest Facebook PHP SDK 4?
Also a quick tutorial on how to use this service provider would be very helpful.
I'm new to Silex and the information here on GitHub is not sufficient for me to understand how to use this properly.

Thanks!

**Comment by maerlyn** [comment]
This service provider uses graph api endpoints directly, does not need (or use) the FB SDK at all.

It uses the old api (v1.0), which is only available till April 30th - and since I stopped writing facebook apps a while ago it may not be upgraded to 2.0.

For a quick tutorial you may see insolis/silex-alap, which was the base app I used for all silex-facebook projects. It shows you how you can handle new users (fb_addhandler) and returning users (in `$app->before`). Unfortunately it uses non-english names in a few places.

If you have any questions, I'll be glad to help.

**Comment by m-vdv** [comment]
Thanks @maerlyn for the quick response!

That explains a lot! 
Would really love to see an upgrade too support the Graph API v2, I don't want to build on the deprecated API (v1.0).

Or maybe you know of any other Silex Service Providers or methods to easily make Facebook calls and login ect that do use the latest API or SDK 4?

**Comment by maerlyn** [comment]
I don't know any. I've checked what changed between apiv1 and apiv2, and the auth part stayed the same, so that part of my provider should work with new applications too. I didn't check the other endpoints, but should not be hard to upgrade them. I may find the time during the weekend, but even so I would not be able to test it.

I would welcome a pull request if you want to upgrade yourself ;)
